export enum Gender {
  Male = 'Male',
  Female = 'Female',
}

export enum MedicalSpecialization {
  Anesthesia = 'Anesthesia',
  Cardiovascular = 'Cardiovascular',
  CommunityHealth = 'CommunityHealth',
  Dentistry = 'Dentistry',
  Dermatology = 'Dermatology',
  DietNutrition = 'DietNutrition',
  Emergency = 'Emergency',
  Endocrine = 'Endocrine',
  Gastroenterologic = 'Gastroenterologic',
  Genetic = 'Genetic',
  Geriatric = 'Geriatric',
  Gynecologic = 'Gynecologic',
  Hematologic = 'Hematologic',
  Infectious = 'Infectious',
  LaboratoryScience = 'LaboratoryScience',
  Midwifery = 'Midwifery',
  Musculoskeletal = 'Musculoskeletal',
  Neurologic = 'Neurologic',
  Nursing = 'Nursing',
  Obstetric = 'Obstetric',
  Oncologic = 'Oncologic',
  Optometric = 'Optometric',
  Otolaryngologic = 'Otolaryngologic',
  Pathology = 'Pathology',
  Pediatric = 'Pediatric',
  PharmacySpecialty = 'PharmacySpecialty',
  Physiotherapy = 'Physiotherapy',
  PlasticSurgery = 'PlasticSurgery',
  Podiatric = 'Podiatric',
  PrimaryCare = 'PrimaryCare',
  Psychiatric = 'Psychiatric',
  PublicHealth = 'PublicHealth',
  Pulmonary = 'Pulmonary',
  Radiography = 'Radiography',
  Renal = 'Renal',
  RespiratoryTherapy = 'RespiratoryTherapy',
  Rheumatologic = 'Rheumatologic',
  SpeechPathology = 'SpeechPathology',
  Surgical = 'Surgical',
  Toxicologic = 'Toxicologic',
  Urologic = 'Urologic',
}

export enum MedicalRecordsActionTypes {
  Generic = 'Generic',
  Diagnosis = 'Diagnosis',
  Surgery = 'Surgery',
  Birth = 'Birth',
  Death = 'Death',
  Illness = 'Illness',
  Allergy = 'Allergy',
  LabTest = 'LabTest',
  AI_TEST = 'AI_TEST',
}

export enum MessageKinds {
  text = 'text',
  image = 'image',
  medicalRecord = 'medicalRecord',
}
