name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DATABASE_URL : ${{ env.DATABASE_URL }}
        JWT_SECRET : ${{ env.JWT_SECRET }}
        RT_SECRET : ${{ env.RT_SECRET }}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
