name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "${{ secrets.DATABASE_URL }}" > .env

    - name: Check environment variable
      run: |
        cat .env
        if [[ -z $(cat .env) ]]; then
          echo "Error: DATABASE_URL environment variable is empty"
          exit 1
        fi

#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag medical-records-server
