name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up environment
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: |
        echo "$ENV_FILE" > .env
    - name: Check environment variable
      run: |
        if [[ -z $DATABASE_URL ]]; then
          echo "Error: DATABASE_URL environment variable is empty"
          exit 1
        fi
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag medical-records-server
